export function graphCommandHelp(): string {
  return [
    "Usage:",
    "  fide graph init [--dir <path>] [--json]",
    "  fide graph add [--target <key-or-path>] '<json>' [--format <json|jsonl|fsd>] [--no-normalize] [--json] [--draft]",
    "  fide graph add [--target <key-or-path>] --in <inputs> [--format <json|jsonl|fsd>] [--no-normalize] [--json] [--draft]",
    "  fide graph add [--target <key-or-path>] --stdin [--format <json|jsonl|fsd>] [--no-normalize] [--json] [--draft]",
    "  fide graph validate --in <input> [--format <json|jsonl|fsd>] [--json]",
    "  fide graph root --in <input> [--format <json|jsonl|fsd>] [--json]",
    "  fide graph status [--target <key-or-path>]",
    "  fide graph query --sql \"<query>\" [--json] [--allow-write]",
    "",
    "Notes:",
    "  - Normalization is ON by default for `graph add`.",
    "  - Without `--target`, graph commands default to the local current working directory unless `.fide/settings.json` provides a legacy graphDir override.",
    "  - `--target <name>` resolves a configured graph target from `.fide/settings.json`.",
    "  - `--target <path>` resolves a local .fide directory path.",
    "  - Configured postgres targets resolve the database URL from `FIDE_GRAPH_DATABASE_URL` first, then target settings.",
    "  - `--draft` writes a statement-doc markdown file to .fide/statement-drafts/YYYY/MM/DD/<root>.md (local targets only).",
    "  - `graph add` accepts inline JSON (default), `--in`, or `--stdin`.",
    "  - `--stdin`/`--in` can auto-detect json/jsonl/fsd, or use --format to force.",
    "  - `validate`/`root` accept statement-doc inputs and json/jsonl batches.",
    "  - `status` reports whether the target directory has a .fide folder.",
  ].join("\n");
}
